# Generated by Django 6.0.7 on 2026-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_add_patient_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('data_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-run_at',),
            },
        ),
    ]
